### ISSUE TITLE
anims not working

### ISSUE THREAD

**Issue by bonboogle** [LastationVRChat/NSFW-GoLoco#16]
### The project version

v1.8.3

### Which Unity Version are you using?

2022.3.22f1

### Describe your issue.

imported the package via vcc it attaches properly but alot of the toggles arre broken from what i can tell its due to the animations for them not working

### Steps to reproduce the problem:

```bash
1.
2.
3.
...
```

### Have you modified the project?

No

### Did the issue happen in-game or on Unity Editor?

Both

**Comment by KuryKat** [comment]
Hey there! I'm sorry for the slow reply, please confirm me if you are *certain* you only imported NSFW GoGo and **not** a normal gogo mixed together? if your avatar comes with built-in gogo **make sure to DISABLE the gogo the avatar is trying to import when importing the avatar!!!!**

**Comment by bonboogle** [comment]
hi yea ive only got the nsfw gogo the avi does not have gogo pre installed

**Comment by KuryKat** [comment]
Thank you for confirming that you've only imported the NSFW GoGo and that your avatar doesn’t have a pre-installed GoGo.

This particular issue hasn’t been reported by other users, which suggests it might be related to your specific setup or configuration. To ensure everything is installed correctly, please double-check the import and setup instructions provided in the documentation. Additionally, if you’re using any third-party assets or modifications, they could potentially interfere with the animations.

Since this seems to be a support-related matter rather than a bug in the package itself, we’ll be closing this issue here. For further assistance, we recommend opening a development ticket in our [Discord server](https://discord.gg/lastation), where we can provide more tailored support.

Thank you for your understanding, and we look forward to helping you resolve this!
